New "neu-crystalgrape" theme
matteobruni/object-gui pull request #75
Opened 2020-10-17 13:55 UTC by kligmasn

2020-10-17 13:56 UTC, kligmasn commented
Themes for Issue #36

2020-10-17 17:24 UTC, matteobruni requested changes

2020-10-17 17:24 UTC, matteobruni commented on src/scss/themes/_neucrystalgrape.scss
> +// $name
Can you please remove all these comments and use variables like the other themes?

There are a lot of repeated colors in the theme below.

2020-10-17 17:24 UTC, matteobruni commented
Please use `yarn` for installing dependencies instead of `npm`.

2020-10-18 22:12 UTC, matteobruni approved these changes

2020-10-18 22:12 UTC, merged